// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccinationWebSite.Data;

#nullable disable

namespace VaccinationWebSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220918220556_AddDataTables")]
    partial class AddDataTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VaccinationWebSite.Model.Conf", b =>
                {
                    b.Property<int>("FourthVaccine")
                        .HasColumnType("int");

                    b.Property<int>("NotificationDays")
                        .HasColumnType("int");

                    b.Property<int>("SecondVaccine")
                        .HasColumnType("int");

                    b.Property<int>("ThirdVaccine")
                        .HasColumnType("int");

                    b.ToTable("Conf");
                });

            modelBuilder.Entity("VaccinationWebSite.Model.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("VaccinationWebSite.Model.Register", b =>
                {
                    b.Property<int>("ID_Person")
                        .HasColumnType("int");

                    b.Property<int>("ID_Vaccine")
                        .HasColumnType("int");

                    b.Property<DateTime>("VaccineDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("VaccinationWebSite.Model.Vaccine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
